hostname: rancherOS
rancher:
  console: debian
  docker:
    ca_cert: |+
      -----BEGIN CERTIFICATE-----
      MIIC0TCCAbmgAwIBAgIQX9jlz6NgWRDTiinkhE+EljANBgkqhkiG9w0BAQsFADAS
      MRAwDgYDVQQKEwdyYW5jaGVyMB4XDTIzMDEwMjE0NDYwMFoXDTI1MTIxNzE0NDYw
      MFowEjEQMA4GA1UEChMHcmFuY2hlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
      AQoCggEBAOI0lBg767F6lA+63HxaQ4sRL1vgS77buP4iQINDyKf6Tt6tGxRpyjcM
      czBRf9TAhE8k4863NOJx1bAD1YCXQh7v6dS+NNeR2fb7NVFvbTvUDfhVaJr0H+iR
      fc9dkNELH24FThvwQnQnkmA6n/xD+De5GAusQ6FeXQ1JriozghzACeIEi4SqFHWC
      RoXJuPxXDY5L3B7PYrJztDJqlVGzvLFuR+fwZ4JN+ACjSOthGIuOu8eCQBLTA3kN
      CFOkMWhQoOrH9v1GwUsxUXy/6LuNwA12TnajIiBqp4FpqOYPdkpXI5+r0ZKAW7F5
      J6WCk0qKHD2q7dI9TWvleUqDzaM/tZcCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKs
      MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBANqoLjCdnLN/iHDo
      j4eTBWho42Z5mFkUGQzLXTHfgzWPKG15ufvc2wHNWDFFY5d9TJ6nRdZuNV1VQICO
      GhBQ9JDummnHuMIJTMu7ExK/mD5Ie6Dc252AuQ28SuDmW4V6sCyHMAaAtfyZ+sIl
      yzPHOVaKTED26CuOfT9BW43o9A1SFyY1+lXu0/fXnBkJ01Ussg3fbNyoG+zYSiqV
      ns/4lTlz6DsadoCO5HYGf076TqLl57Df7hmPNxux9AM8yIGCDRA8zGyctr2kg/pz
      s64DCkXDcXmYnuG+RYEugfpzfELbnesspYPWQGZrRskkqcjZZabKFZZpqpd1BBYC
      sAQfdio=
      -----END CERTIFICATE-----
    ca_key: |+
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEA4jSUGDvrsXqUD7rcfFpDixEvW+BLvtu4/iJAg0PIp/pO3q0b
      FGnKNwxzMFF/1MCETyTjzrc04nHVsAPVgJdCHu/p1L4015HZ9vs1UW9tO9QN+FVo
      mvQf6JF9z12Q0QsfbgVOG/BCdCeSYDqf/EP4N7kYC6xDoV5dDUmuKjOCHMAJ4gSL
      hKoUdYJGhcm4/FcNjkvcHs9isnO0MmqVUbO8sW5H5/Bngk34AKNI62EYi467x4JA
      EtMDeQ0IU6QxaFCg6sf2/UbBSzFRfL/ou43ADXZOdqMiIGqngWmo5g92Slcjn6vR
      koBbsXknpYKTSoocPart0j1Na+V5SoPNoz+1lwIDAQABAoIBAAQRxBRHh67ysJUz
      3GGUUiC/V2XEvDgbxdE0loqF/qce9qpE3PbaDFw/KhdVcAJI0FiIJl0CqL3mJFz9
      RKsCjZr23/MG1PaH1i7+R/BGG+X2o6WzC6W1/Jj3fRbs7P0FwTP+fnA8O0XRrG10
      wIoOQvnlp4wWNkVB6FSj3bE+qfmQZjKHJ1uglFHOLFxax14RfC2GOcIcipChy0+U
      N7eVzbj3HcInQbMOeIeW/UVNxJd9HE25eP9oyVrTYcz1CiCBa7uv+VdlTRAUFwhm
      zGN1vL4Ya2qWidB1cbSbAnowudj1fWj2IMX+9YkE5b3hPba1HcNXYtgsljCktn3V
      yZIgeIECgYEA+zcwnGkpTuvjCGF7KJ1DQWwz4Cz/z43jHvrxbDwEQ1zUFndYpmaC
      qSggu0Tluao7JGRHqyonVpVMiCxMSg1hMpvcJtfMZVaYJOFhSbfe7WZpRm5GoZma
      UxGtCma2lnB860hHbLNL/dhQpVrjt6PRjKGK58hcSov6qRJryj8VKdcCgYEA5oNz
      VaRPfnOVpx6hkbUYFixtsL5JBcBjbnxoKOkPYUdkZ3KLMUxlIMzjpGK6XKczEQSb
      e78+ucjidFrWsPQcwohO0c2d3pZUUaFE0/BUqyuvHmVN3eT+U46hrTgVVnlfPhsh
      I+wS0BCmf4RhtveICcGoIDCm9SU0LNDlHa7Z2kECgYAmZaQfdA9lSba01Dl/1rGt
      8TzomdgrwDMjzBVUhsPcC/c6y9kX7fkwo7qFBR3byAIsKMuvhMzodf9xnNu4Qd1G
      X/5BTaCnKJouoOg+3UTMomea5UYUcybcZYo+Wb60tdLSH4UTP0BxNzv0WjUOH5Lq
      3NIfZUd9+XFBoFgrXIL+lwKBgGTct6aNksr9wEmzuXaMCtII9qYTXNhLajZ58QmV
      kMk7987b69PSXZ2QiTrwiCLqdgnIPlBTShr4rz3CUZZz+fGUuwhKM/2lQZfGPNuP
      mTycjK98HCovfKkLC+tDUvLXgLkoHcQeE80+u9uoDSmF/dxnBC2xnBw//yhs7xOh
      4mkBAoGAa34cfm/8BQllo4DNUMtzmyD931Xx8iv2R6JGfslACrVDpVKcf9za7Uxp
      EcUiSPE/W9sFfUwGfMXMXCtFVY9LHWR6DOUl5WA3msdLcjjpV/FGubuwnl9JaVK/
      xHL7MaOzQxP+ugmUzddR09DqWXefK8C6NUn65t31B0cNj+kkaGk=
      -----END RSA PRIVATE KEY-----
    engine: docker-19.03.9
    tls: false
  keyboard-configuration: fr-FR
  network:
    interfaces:
      eth0:
        address: 172.20.51.16/24
        gateway: 172.20.51.1
  services_include:
    kernel-extras: true
    kernel-headers: true
    kernel-headers-system-docker: true
    qemu-guest-agent: true
  ssh:
    keys:
      dsa: |+
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABsgAAAAdzc2gtZH
        NzAAAAgQDn5EUELoFabN4Q0SlzkvgN96rI1QW4FDdfDYDsICJkC+hQ/zFD81aoGXaj3Y9F
        4aRJBbkxDAa/Rz/3+xJ1mzavpGcN/IOYy75vW4W1f0es2roeOVqybgNWLlJm+IBXd7g1Ia
        rOOLWuuaXDlLp5larfwQ8t+pB8tqz9RNMhgwYtMQAAABUA5lqcVS/KD+Vq/Ym6v1torWQr
        XaEAAACBAKdBMAn8+mrl7MDEe1iV8JWUtS+qOACp0PS2Fs6X1/c3m44GT0+xS1GK+Y6W+B
        TBWT7FRzKW8v6iN+ma0Fn/0F3y66U3tXCnOaLSbhokxwQJxS71Qs51pXqlZwhlujODNXrL
        Akez1kTOrnof2YVY60WViFzTebEVLHY6o7ME6ucLAAAAgEUCLNZ7/sMYCOlK8Wwhpcgv9A
        QIEHqXZfHXiYUrbnkD/zTFjNfdrSpG9Y+zGECSV4v+etUJDlu7TOlBp9PeEKrHHcJch10K
        dzTX0CT85SBMws9uVKClwz69koSvF14pzYpYKMVWNSjQpj+IyO+IiaIwiWx8RmviyFVGxp
        /XDIG8AAAB6L1rowK9a6MCAAAAB3NzaC1kc3MAAACBAOfkRQQugVps3hDRKXOS+A33qsjV
        BbgUN18NgOwgImQL6FD/MUPzVqgZdqPdj0XhpEkFuTEMBr9HP/f7EnWbNq+kZw38g5jLvm
        9bhbV/R6zauh45WrJuA1YuUmb4gFd3uDUhqs44ta65pcOUunmVqt/BDy36kHy2rP1E0yGD
        Bi0xAAAAFQDmWpxVL8oP5Wr9ibq/W2itZCtdoQAAAIEAp0EwCfz6auXswMR7WJXwlZS1L6
        o4AKnQ9LYWzpfX9zebjgZPT7FLUYr5jpb4FMFZPsVHMpby/qI36ZrQWf/QXfLrpTe1cKc5
        otJuGiTHBAnFLvVCznWleqVnCGW6M4M1essCR7PWRM6ueh/ZhVjrRZWIXNN5sRUsdjqjsw
        Tq5wsAAACARQIs1nv+wxgI6UrxbCGlyC/0BAgQepdl8deJhStueQP/NMWM192tKkb1j7MY
        QJJXi/561QkOW7tM6UGn094QqscdwlyHXQp3NNfQJPzlIEzCz25UoKXDPr2ShK8XXinNil
        goxVY1KNCmP4jI74iJojCJbHxGa+LIVUbGn9cMgbwAAAAUFx06NYdumOhBEP00P6TdhqgR
        3OoAAAAMcm9vdEByYW5jaGVyAQIDBAUG
        -----END OPENSSH PRIVATE KEY-----
      dsa-pub: |+
        ssh-dss AAAAB3NzaC1kc3MAAACBAOfkRQQugVps3hDRKXOS+A33qsjVBbgUN18NgOwgImQL6FD/MUPzVqgZdqPdj0XhpEkFuTEMBr9HP/f7EnWbNq+kZw38g5jLvm9bhbV/R6zauh45WrJuA1YuUmb4gFd3uDUhqs44ta65pcOUunmVqt/BDy36kHy2rP1E0yGDBi0xAAAAFQDmWpxVL8oP5Wr9ibq/W2itZCtdoQAAAIEAp0EwCfz6auXswMR7WJXwlZS1L6o4AKnQ9LYWzpfX9zebjgZPT7FLUYr5jpb4FMFZPsVHMpby/qI36ZrQWf/QXfLrpTe1cKc5otJuGiTHBAnFLvVCznWleqVnCGW6M4M1essCR7PWRM6ueh/ZhVjrRZWIXNN5sRUsdjqjswTq5wsAAACARQIs1nv+wxgI6UrxbCGlyC/0BAgQepdl8deJhStueQP/NMWM192tKkb1j7MYQJJXi/561QkOW7tM6UGn094QqscdwlyHXQp3NNfQJPzlIEzCz25UoKXDPr2ShK8XXinNilgoxVY1KNCmP4jI74iJojCJbHxGa+LIVUbGn9cMgbw= root@rancher
      ecdsa: |+
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
        1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQTSwuJQZFGhd0nr17FEGrRMAlu5c4tl
        cYPuHBlDc0aTrAsDfrn+Us7o1nCJXAOzlXv/eEbOoipYL6bGnJTdAVCCAAAAqF+Bz5xfgc
        +cAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNLC4lBkUaF3SevX
        sUQatEwCW7lzi2Vxg+4cGUNzRpOsCwN+uf5SzujWcIlcA7OVe/94Rs6iKlgvpsaclN0BUI
        IAAAAhAOFunmyqsy2zTTPoocvlqbj4XZsqvi5vt+jWscNFEGCFAAAADHJvb3RAcmFuY2hl
        cgECAw==
        -----END OPENSSH PRIVATE KEY-----
      ecdsa-pub: |+
        ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNLC4lBkUaF3SevXsUQatEwCW7lzi2Vxg+4cGUNzRpOsCwN+uf5SzujWcIlcA7OVe/94Rs6iKlgvpsaclN0BUII= root@rancher
      ed25519: |+
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACAYwL08++M49ub8r8WdIFfYDn8amDituEmnZX+C0Xcp1wAAAJBXOLKCVziy
        ggAAAAtzc2gtZWQyNTUxOQAAACAYwL08++M49ub8r8WdIFfYDn8amDituEmnZX+C0Xcp1w
        AAAECInuETksRaxRC0G+iYwABorloX+ENaMXxwBnbsmzcmYxjAvTz74zj25vyvxZ0gV9gO
        fxqYOK24Sadlf4LRdynXAAAADHJvb3RAcmFuY2hlcgE=
        -----END OPENSSH PRIVATE KEY-----
      ed25519-pub: |+
        ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjAvTz74zj25vyvxZ0gV9gOfxqYOK24Sadlf4LRdynX root@rancher
      rsa: |+
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAQEAuv/e4IwweaigTtFszIaacO3591LSlb7wLMy4pBb9uIMzUwgyd9xw
        PyxHMpHqgL4TS3PrlbhVWed0j6VZ9fo73dW8drFZky9Pi5So0X5ZrkqBNx0cwcnMf37CPC
        Nj6i4hVOm94qkFeZsqsVxCudiURnmP5zA5NleAlvvYv0VSBjpuV3/hKOuhCLyMlhajc/xw
        cCAeBhiUh2/8Lpsu9ybGsYZpE3JVUYVKD8mhJ8Z8REogmupq9feeFyt/TOuU9R2JBn9Soh
        jlRDj9e8Y07bbfhPsOSgTNSVsA8n82lgI7PPCNeHXpjSFv0hLDW98xsm5cNbnm+V3CtxjO
        pllcC3KQEQAAA8gbRbEKG0WxCgAAAAdzc2gtcnNhAAABAQC6/97gjDB5qKBO0WzMhppw7f
        n3UtKVvvAszLikFv24gzNTCDJ33HA/LEcykeqAvhNLc+uVuFVZ53SPpVn1+jvd1bx2sVmT
        L0+LlKjRflmuSoE3HRzBycx/fsI8I2PqLiFU6b3iqQV5myqxXEK52JRGeY/nMDk2V4CW+9
        i/RVIGOm5Xf+Eo66EIvIyWFqNz/HBwIB4GGJSHb/wumy73JsaxhmkTclVRhUoPyaEnxnxE
        SiCa6mr1954XK39M65T1HYkGf1KiGOVEOP17xjTttt+E+w5KBM1JWwDyfzaWAjs88I14de
        mNIW/SEsNb3zGyblw1ueb5XcK3GM6mWVwLcpARAAAAAwEAAQAAAQAYryvxgi/n701x+g0d
        lmsOmytS7Xjk0XaMw11gM7S8RX1h6YQX9F5QyHyBfWdyJSUQ4bVoZxPFMVteltogMS7z4o
        HlPRXw6t7aMv5x4PbfnfAeoVYpcoTvE4F6RMWspPg7aDtrjxos6kGhdedM9vzjrKpFP0Ve
        GgDcbVQ4M2NXdOb8OwNug7shvYqkPcPQf1SX4WlBbOxXzIbHOcq6mNuW6DbDJe7Jc8k3++
        I5W+xxQr2Irsmqvbj1fMdhnc2g8lcYeujySDNaOwZszhv0kWHXTANjBnCDXLoiFLBsZMKN
        2TwjCTr6swSp2co47PyvF0YnK3cUH0K/FXeY0UHWPy69AAAAgE63nb/qZ1bpsfN7s+D2s7
        WJ8TzlpZJxetEHl7XOA1dYGJ1f5zTMEhrHiqvoykAscb8ch2daleL6vygVZFqeskTCNehY
        kiyQDTDKhhgdMytqnOyn9bvlWnJ16QQgrQ0wN0xhEqkRtNv6lO8mLJztRpve5vQtIziGXI
        CwS/ZagrN2AAAAgQD0URMlmhh+TG+Ceqf4Q91hVk0p0YHhpaoHskzRbkTVNHdqdhsvf0dm
        frl6OhsOe2YWrCsJCgFTh3KjtCTR/ZSntOy1iQgQLb3tZCZCR/SyJYDTOax/ixI9DeQUjK
        1oNNbv5FqDFJYcwj+/NPIvwr33IpytN7c39ZrQQMTvSt8UGwAAAIEAw/EeWoKgx9g+0vRF
        Jkhh549N0NF63A10cRM1TWVEH7fVgdgeeycu7NXzPAzENAQKKMjUralWzKvIdOaoL5Opqr
        J8d1zMIXOvJ6cKi48Fmu6PEqPdsDOb9o9i7EPylKJANDGOEZLZ/6zxs28BcAQb1gOW9aXi
        HVCIibURbnQjt0MAAAAMcm9vdEByYW5jaGVyAQIDBAUGBw==
        -----END OPENSSH PRIVATE KEY-----
      rsa-pub: |+
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6/97gjDB5qKBO0WzMhppw7fn3UtKVvvAszLikFv24gzNTCDJ33HA/LEcykeqAvhNLc+uVuFVZ53SPpVn1+jvd1bx2sVmTL0+LlKjRflmuSoE3HRzBycx/fsI8I2PqLiFU6b3iqQV5myqxXEK52JRGeY/nMDk2V4CW+9i/RVIGOm5Xf+Eo66EIvIyWFqNz/HBwIB4GGJSHb/wumy73JsaxhmkTclVRhUoPyaEnxnxESiCa6mr1954XK39M65T1HYkGf1KiGOVEOP17xjTttt+E+w5KBM1JWwDyfzaWAjs88I14demNIW/SEsNb3zGyblw1ueb5XcK3GM6mWVwLcpAR root@rancher
    listen_address: 172.20.51.16
    port: 22