apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <VOLUME_NAME>
  namespace: <NAMESPACE_NAME>
  labels:
    app: <APP_NAME>
spec:
  accessModes: 
    - <ACCESS_MODES> #ReadWriteOnce - ReadOnlyMany - ReadWriteMany - ReadWriteOncePod
  resources:
    requests:
      storage: <STORAGE_SIZE>
  # ---
  # Digital Ocean
  # storageClassName: do-block-storage
  # ---
  # AWS
  # storageClassName: aws-ebs
  # ---
  # Azure
  # storageClassName: azure-disk
  # ---
  # GCE PD
  # storageClassName: gce-pd
  # ---
  # CIVO
  # storageClassName: civo-volume
  # ---
