apiVersion: apps/v1
kind: Deployment
metadata:
  name: <DEPLOYMENT_NAME> # Name of the deployment
  namespace: <NAMESPACE_NAME> # Name of the namespace
  labels:
    app: <APP_NAME> # Name of your application
spec:
  selector:
    matchLabels:
      app: <APP_NAME> # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: <APP_NAME> # Name of your application
    spec:
      containers:
      # Containers are the individual pieces of your application that you want
      # to run.
      - name: <CONTAINER_NAME> # Name of the container
        image: <CONTAINER_IMAGE>:<TAG> # The image you want to run
        # resources:
        #   limits:
        #     memory: 512Mi
        #     cpu: "1"
        #   requests:
        #     memory: 256Mi
        #     cpu: "0.2"
        ports:
        # Ports are the ports that your application uses.
        - containerPort: 8080 # The port that your application uses
        volumeMounts: #Bind Mounts for your application
        # VolumeMounts are the bind mounts that your application uses.
        - mountPath: <PATH_USED_BY_APP> # The path that your application uses
          name: <BIND_MOUNT_NAME> # Name of the volume
      volumes: #Volumes for your application
      # Volumes are the persistent storage that your application uses.
      - name: <VOLUME_NAME> # Name of the volume
        persistentVolumeClaim:
          claimName: <PERSISTENTVOLUMECLAIM_NAME> # Name of the persistent volume claim